name: Auto Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy on VM
        run: |
          cd coffee-web
          git pull origin main
          docker compose up -d --build
